# This is a basic workflow to help you get started with Actions

name: Check version change

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Check if version was changed
        run: |
          if [[ $(git diff origin/develop Version.h) ]]; then
            echo "Version was changed"
            exit 0 
          else
            echo "No version change detected"
            exit 1 
          fi
